### ISSUE TITLE
Can this guarantee "uniqueness"?

### ISSUE THREAD

**Issue by williamokano** [sharadbhat/ReadableURL#5]
Using uuid will give me amazing "uniquess" on the generated ID, although it's not readable, which is the main purpose of this package.

How unique, or reliable, can this package be to generate words as ID's?

**Comment by sharadbhat** [comment]
Hey William, sorry for the late reply. I haven't really tested the uniqueness of this. But it's better to be on the safe side and not use this for generating IDs.
